name: complex-input-expressions-test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: build image
        uses: ./actions/build
        with:
          image_name: myapp
